name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # - name: List build directory contents
      #   run: ls -la build
      
      # - name: Ensure build directory is not empty
      #   run: |
      #     if [ -z "$(ls -A build)" ]; then
      #       echo "Build directory is empty. Exiting."
      #       exit 1
      #     fi

      - name: Create arti
        run: tar -czf build.tar.gz -C build .

      - name: Upload build arti
        uses: actions/upload-artifact@v2
        with:
          name: build-arti
          path: build.tar.gz

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: 13.233.149.230
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/"
          target: "/var/www/html/react"

      - name: SSH into EC2 and restart server
        uses: appleboy/ssh-action@master
        with:
          host: 13.233.149.230
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart nginx
